[package]
name = "rust-folder-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
csv = "1.3.0"
env_logger = "0.11.5"
log = "0.4.22"
rayon = "1.10.0"
serde = {version = "1.0.204", features=["derive"]}
serde_json = "1.0.122"

[profile.release] 
opt-level=3
debug = true
